# Generated by Django 2.2.21 on 2021-10-15 02:33

from django.db import migrations, models
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ccrpc_collect', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPointSpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('picture', models.ImageField(upload_to='')),
                ('Datatype', models.CharField(choices=[('Recording', 'Recording'), ('Observation', 'Observation'), ('Feedback', 'Feedback')], max_length=256)),
                ('geom', djgeojson.fields.GeometryCollectionField()),
            ],
        ),
        migrations.DeleteModel(
            name='MushroomSpot',
        ),
    ]
